import { GoogleGenAI, Type, Chat } from "@google/genai";
import type { DailyHabits, EcoSuggestion, FootprintData, GroundedResponse, Habit, AgeGroup } from '../types';
import { INDIA_GRID_EMISSION_FACTOR } from '../constants';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

function formatHabitsForPrompt(habits: DailyHabits): string {
  const travelSummary = habits.travel.map(t => `${t.mode}: ${t.distance}km`).join(', ') || 'No travel logged.';
  const shoppingSummary = habits.shopping.map(s => `${s.item} (${s.material})`).join(', ') || 'No clothing shopping logged.';
  const electronicsSummary = habits.electronics.map(e => e.item).join(', ') || 'No electronics purchased.';
  return `The user's recent habits include: Travel -> ${travelSummary}. Clothing -> ${shoppingSummary}. Electronics -> ${electronicsSummary}.`;
}


/**
 * Cleans up text generated by the AI to remove common artifacts.
 * @param text The raw text from the Gemini API.
 * @returns Cleaned text ready for display.
 */
function cleanGeneratedText(text: string): string {
    let cleaned = text.trim();

    // Remove hashtags (e.g., #sustainability)
    cleaned = cleaned.replace(/#\w+/g, '');

    // Remove markdown-style quotes at the beginning of lines
    cleaned = cleaned.replace(/^> /gm, '');

    // Remove markdown bolding and italics which can look out of place
    cleaned = cleaned.replace(/(\*\*|__)(.*?)\1/g, '$2');
    cleaned = cleaned.replace(/(\*|_)(.*?)\1/g, '$2');

    // Trim leading/trailing whitespace again after replacements
    cleaned = cleaned.trim();

    // Remove surrounding quotes if the whole text is wrapped
    if ((cleaned.startsWith('"') && cleaned.endsWith('"')) || (cleaned.startsWith("'") && cleaned.endsWith("'"))) {
        cleaned = cleaned.substring(1, cleaned.length - 1);
    }
    
    // Consolidate multiple newlines into a maximum of two
    cleaned = cleaned.replace(/\n{3,}/g, '\n\n');

    return cleaned.trim();
}


export async function getEcoSuggestions(habits: DailyHabits): Promise<EcoSuggestion[]> {
  const model = "gemini-2.5-flash";

  const prompt = `You are an expert sustainability coach for a user in India. Your mission is to generate 3 actionable and creative eco-friendly suggestions.

**User Context:**
- Location: India
- Recent Habits: ${formatHabitsForPrompt(habits)}

**--- TASK: GENERATE EXACTLY 3 SUGGESTIONS ---**

1.  **One India-Specific Environmental/Cultural Suggestion:**
    -   This suggestion should be relevant to India as a whole but can draw from a specific regional example if it's widely known or applicable (e.g., related to a major festival, a common agricultural practice, or a national conservation project).
    -   Its description must explain both its environmental and cultural benefits.

2.  **Two Habit-Based Suggestions:**
    -   These must be directly inspired by the user's logged habits (travel, shopping, electronics).
    -   Make them specific and actionable. For example, if they bought a polyester shirt, suggest a specific Indian natural textile like Khadi or Kalamkari cotton as a swap, explaining the benefits.

**Output Rules:**
- Provide a catchy, inspiring title.
- Keep descriptions concise (1-3 sentences).
- **FORBIDDEN GENERIC ADVICE:** Do not give generic advice like "use less plastic," "buy local," or "reduce, reuse, recycle." All advice must be specific.`;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            suggestions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: {
                    type: Type.STRING,
                    description: "A short, catchy title for the eco-friendly swap."
                  },
                  description: {
                    type: Type.STRING,
                    description: "A concise, actionable description (1-3 sentences). For the India-specific suggestion, this MUST explain both its environmental and cultural/heritage benefits."
                  }
                },
                required: ["title", "description"]
              }
            }
          },
          required: ["suggestions"]
        },
      },
    });

    const jsonString = response.text.trim();
    // Use a try-catch block for robust JSON parsing, even with responseSchema.
    try {
        const parsed = JSON.parse(jsonString);
        return parsed.suggestions || [];
    } catch (parseError) {
        console.error("Gemini API returned non-JSON response for suggestions:", jsonString, parseError);
        return []; // Return an empty array on parsing failure.
    }
  } catch (error) {
    console.error("Error fetching suggestions from Gemini API:", error);
    throw new Error("Failed to generate eco suggestions.");
  }
}


export async function getCarbonSavingsPrediction(footprint: FootprintData, swap: EcoSuggestion, monthlyGoal?: number): Promise<string> {
    const model = "gemini-2.5-flash";
    
    const goalContext = monthlyGoal ? `*   The user has a monthly goal of ${monthlyGoal} kg CO2e.` : '';

    const prompt = `You are an encouraging AI assistant in an eco-friendly app. Your task is to predict the carbon savings for a user's proposed action and frame it as progress towards their goal.

**User's Data:**
*   Periodic Footprint: ${footprint.total} kg CO2e (Travel: ${footprint.breakdown.travel}kg, Shopping: ${footprint.breakdown.shopping}kg, Electronics: ${footprint.breakdown.electronics}kg).
*   Proposed Eco-Swap: "${swap.title}: ${swap.description}".
${goalContext}

**Your Task & Output Rules (ABSOLUTE - FOLLOW EXACTLY):**
You must generate a single, encouraging sentence predicting the potential monthly carbon savings.
1.  **SINGLE SENTENCE ONLY.** Your entire response must be one sentence. No greetings, no explanations.
2.  **IF GOAL IS PROVIDED:** Your sentence **MUST** use this exact format: "You could save X kg CO2e, getting you Y% closer to your monthly goal!"
    *   Calculate Y as (X / monthlyGoal) * 100. Round to a whole number.
3.  **IF NO GOAL IS PROVIDED:** Your sentence **MUST** use this exact format: "That's a potential saving of X kg CO2e per month!"
4.  **NO MARKDOWN.** Do not use any markdown like asterisks or bolding.

Generate the prediction sentence now.`;

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: prompt,
        });

        return cleanGeneratedText(response.text);

    } catch (error) {
        console.error("Error fetching prediction from Gemini API:", error);
        throw new Error("Failed to generate prediction.");
    }
}

// FIX: Add missing getTravelCo2e function for the CO2 Calculator component.
export async function getTravelCo2e(from: string, to: string): Promise<{ co2e: number }> {
    const model = "gemini-2.5-flash";

    const prompt = `You are a carbon footprint calculator. Calculate the estimated round-trip CO2e emissions in kilograms for a standard gasoline car journey between ${from} and ${to}.
    
Use Google Search to find the one-way driving distance in kilometers.
    
Assume an average emission factor for a standard gasoline car.
    
Your final output MUST be a JSON object with a single key "co2e" which is a number representing the total round-trip kilograms of CO2e.`;

    try {
        const response = await ai.models.generateContent({
            model,
            contents: prompt,
            config: {
                tools: [{ googleSearch: {} }],
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        co2e: {
                            type: Type.NUMBER,
                            description: "The total round-trip CO2e emissions in kilograms."
                        }
                    },
                    required: ["co2e"]
                }
            }
        });

        const jsonString = response.text.trim();
        try {
            const parsed = JSON.parse(jsonString);
            return parsed;
        } catch (e) {
            console.error("Gemini API returned non-JSON response for travel CO2e:", jsonString, e);
            throw new Error("Could not parse the travel CO2e response.");
        }
    } catch (error) {
        console.error("Error fetching travel CO2e from Gemini API:", error);
        throw new Error("Failed to generate travel CO2e.");
    }
}

export async function getLatestSustainabilityNews(): Promise<GroundedResponse> {
    const model = "gemini-2.5-flash";

    const prompt = `You are an expert news curator for an environmental app. Your task is to provide a summary of 4 recent, relevant, and unique news articles about sustainability, environmental conservation, or eco-friendly initiatives in India. Synthesize the key information from these articles into an engaging overview for our users.`;

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: prompt,
            config: {
                tools: [{googleSearch: {}}],
            },
        });
        
        const summary = cleanGeneratedText(response.text);
        const rawSources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
        
        const sources = rawSources.map((chunk: any) => ({
            title: chunk.web.title,
            uri: chunk.web.uri,
        })).filter((source: any) => source.uri);

        return { summary, sources };

    } catch (error) {
        console.error("Error fetching news from Gemini API:", error);
        throw new Error("Failed to fetch latest news.");
    }
}

// FIX: Add missing getStateCarbonReports function.
export async function getStateCarbonReports(state: string): Promise<GroundedResponse> {
    const model = "gemini-2.5-flash";

    const prompt = `You are an expert news curator for an environmental app. Your task is to provide a summary of recent, relevant news articles and government reports about sustainability, carbon emissions, environmental conservation, or eco-friendly initiatives specifically for the state of ${state} in India. Synthesize the key information from these sources into an engaging overview for our users.`;

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: prompt,
            config: {
                tools: [{googleSearch: {}}],
            },
        });
        
        const summary = cleanGeneratedText(response.text);
        const rawSources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
        
        const sources = rawSources.map((chunk: any) => ({
            title: chunk.web.title,
            uri: chunk.web.uri,
        })).filter((source: any) => source.uri);

        return { summary, sources };

    } catch (error) {
        console.error(`Error fetching carbon reports for ${state} from Gemini API:`, error);
        throw new Error(`Failed to fetch carbon reports for ${state}.`);
    }
}

export async function getGridEmissionFactor(): Promise<number> {
  // This function is now simplified to return a constant, removing the Gemini call.
  return Promise.resolve(INDIA_GRID_EMISSION_FACTOR);
}

export interface PlantBasedSwap {
  title: string;
  description: string;
  reductionPercentage: number;
}

export async function getPlantBasedSwapSuggestion(servings: number): Promise<{ swap: PlantBasedSwap }> {
  const model = "gemini-2.5-flash";

  const prompt = `You are a personalized food impact coach. A user eats red meat ${servings} time(s) per week. Your task is to generate ONE highly specific and actionable plant-based substitution that provides a similar protein content and texture.

Using Google Search, find comparative data on the CO₂e emissions for red meat (like beef or mutton) and the specific plant-based substitute you choose.

Based on this data, calculate and state the approximate percentage CO₂e reduction for making this single swap.`;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }],
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            swap: {
              type: Type.OBJECT,
              properties: {
                title: {
                  type: Type.STRING,
                  description: "A catchy, short title for the swap, e.g., 'Swap Beef Burgers for Lentil Burgers'."
                },
                description: {
                  type: Type.STRING,
                  description: "A short, actionable description of the substitution, highlighting protein/texture similarities."
                },
                reductionPercentage: {
                  type: Type.NUMBER,
                  description: "The approximate percentage reduction in CO2e for this specific swap, as a whole number."
                }
              },
              required: ["title", "description", "reductionPercentage"]
            }
          },
          required: ["swap"]
        }
      }
    });

    const jsonString = response.text.trim();
    try {
      const parsed = JSON.parse(jsonString);
      return parsed;
    } catch (e) {
      console.error("Gemini API returned non-JSON response for food swap:", jsonString, e);
      throw new Error("Could not parse the food swap suggestion.");
    }

  } catch (error) {
    console.error("Error fetching food swap from Gemini API:", error);
    throw new Error("Failed to generate food swap suggestion.");
  }
}

export async function getHabitDiscoverySuggestions(interests: string, ageGroup: AgeGroup | undefined, dailyRoutine: string): Promise<Habit[]> {
    const model = "gemini-2.5-flash";
    const prompt = `You are an eco-habit discovery assistant.
Based on this user profile: {interests: ${interests}}, {age_group: ${ageGroup || 'any'}}, {daily_routine: ${dailyRoutine}}, suggest 5 realistic eco-friendly habits that fit their lifestyle.

The user is in India. Prioritize novelty and youth relevance, especially considering what someone in the '${ageGroup || 'any'}' age group might find appealing. Do not suggest anything that requires knowing their specific city.

Each habit should include:
- One-line description
- Estimated CO₂ reduction per week
- Level of commitment (Low/Medium/High)`;

    try {
        const response = await ai.models.generateContent({
            model,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        habits: {
                            type: Type.ARRAY,
                            items: {
                                type: Type.OBJECT,
                                properties: {
                                    description: {
                                        type: Type.STRING,
                                        description: "A one-line description of the habit."
                                    },
                                    co2Reduction: {
                                        type: Type.STRING,
                                        description: "Estimated CO₂ reduction per week, e.g., '≈ 0.5 kg CO₂e'"
                                    },
                                    commitment: {
                                        type: Type.STRING,
                                        enum: ['Low', 'Medium', 'High'],
                                        description: "The level of commitment required (Low, Medium, or High)."
                                    }
                                },
                                required: ["description", "co2Reduction", "commitment"]
                            }
                        }
                    },
                    required: ["habits"]
                }
            }
        });

        const jsonString = response.text.trim();
        try {
            const parsed = JSON.parse(jsonString);
            return parsed.habits || [];
        } catch (e) {
            console.error("Gemini API returned non-JSON response for habit discovery:", jsonString, e);
            throw new Error("Could not parse the habit discovery response.");
        }
    } catch (error) {
        console.error("Error fetching habit discovery from Gemini API:", error);
        throw new Error("Failed to generate habit discovery suggestions.");
    }
}

export function startChatSession(): Chat {
    const systemInstruction = `You are CarboLoom AI, a friendly and knowledgeable eco-assistant for a user in India. Your goal is to help users understand their carbon footprint and live more sustainably.
- Keep your answers concise (2-4 sentences) and easy to understand.
- Be encouraging and positive.
- Focus on actionable advice relevant to an Indian context where possible.
- Do not use markdown formatting. Just provide plain text.
- If you don't know an answer, say so politely.`;

    const chat = ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: systemInstruction,
        },
    });
    return chat;
}